import { useEffect, useRef, useState } from "preact/hooks";
import type { Curve, Sample } from "../lib/types.ts";

interface BinPoint { voltage: number; pP90: number; confidence: number; sampleCount: number }
interface Metrics {
  envelope: BinPoint[];
  recommendation: { voltage: number; power: number }[] | null;
  energy: { kwh: number };
  stalls: { count: number; hotspots: { vBand: [number, number]; count: number }[] };
  window: { mpptSampleCount: number };
}

const V_MIN = 45;
const V_MAX = 145;
const W_MIN = 0;
const W_MAX = 5500;

function project(v: number, w: number, width: number, height: number, pad: number): [number, number] {
  const x = pad + ((v - V_MIN) / (V_MAX - V_MIN)) * (width - pad * 2);
  const y = height - pad - ((w - W_MIN) / (W_MAX - W_MIN)) * (height - pad * 2);
  return [x, y];
}

interface VerdictResp {
  label: "BETTER" | "WORSE" | "MIXED" | "INSUFFICIENT_DATA" | "INCOMPARABLE";
  detail: { kwhPerHourDelta: number; stallsPerDayDelta: number } | null;
  activeCurveName?: string;
  previousCurveName?: string;
}

export default function ScatterPlot({ curve }: { curve: Curve | null }) {
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const [samples, setSamples] = useState<Sample[]>([]);
  const [metrics, setMetrics] = useState<Metrics | null>(null);
  const [verdict, setVerdict] = useState<VerdictResp | null>(null);
  const [showSuggested, setShowSuggested] = useState(true);
  const [freeRecommendation, setFreeRecommendation] = useState<{ voltage: number; power: number }[] | null>(null);
  const [showFree, setShowFree] = useState(true);
  const [applyBusy, setApplyBusy] = useState(false);
  const [applyMsg, setApplyMsg] = useState<string | null>(null);

  useEffect(() => {
    const now = Math.floor(Date.now() / 1000);
    const from = now - 7 * 86400;
    fetch(`/api/samples?from=${from}&to=${now}`).then((r) => r.json()).then((j) => setSamples(j.rows));
    if (curve) {
      fetch("/api/analyze", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ curveId: curve.id, tsFrom: from, tsTo: now }),
      }).then((r) => r.json()).then(setMetrics);
    }
    fetch("/api/recommend-free", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({}),
    }).then((r) => r.json()).then((j) => setFreeRecommendation(j.recommendation ?? null));
    fetch("/api/verdict").then((r) => r.json()).then(setVerdict);
  }, [curve?.id]);

  const applySuggested = async () => {
    if (!metrics?.recommendation) return;
    const stamp = new Date().toISOString().slice(0, 16).replace("T", "-").replace(":", "");
    const name = `auto-${stamp}`;
    setApplyBusy(true);
    setApplyMsg(null);
    const res = await fetch("/api/curves", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        name,
        notes: "Generated by analyzer. Load on TriStar before activating.",
        source: "suggested",
        points: metrics.recommendation,
      }),
    });
    setApplyBusy(false);
    if (res.ok) {
      setApplyMsg(`Created '${name}'. Open the drawer to activate it after loading on the TriStar.`);
    } else {
      const err = await res.json().catch(() => ({}));
      setApplyMsg(`Failed: ${err.error ?? res.statusText}`);
    }
  };

  useEffect(() => {
    const cv = canvasRef.current;
    if (!cv) return;
    const ctx = cv.getContext("2d");
    if (!ctx) return;
    const W = cv.width;
    const H = cv.height;
    const PAD = 40;

    ctx.fillStyle = "#181a1f";
    ctx.fillRect(0, 0, W, H);

    // Axes
    ctx.strokeStyle = "#444a55";
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(PAD, H - PAD);
    ctx.lineTo(W - PAD, H - PAD);
    ctx.moveTo(PAD, H - PAD);
    ctx.lineTo(PAD, PAD);
    ctx.stroke();

    // Axis labels
    ctx.fillStyle = "#8a8f98";
    ctx.font = "11px system-ui";
    for (let v = 50; v <= 140; v += 10) {
      const [x, _y] = project(v, 0, W, H, PAD);
      ctx.fillText(`${v}V`, x - 10, H - PAD + 14);
    }
    for (let w = 0; w <= 5000; w += 1000) {
      const [_x, y] = project(0, w, W, H, PAD);
      ctx.fillText(`${w}W`, 4, y + 4);
    }

    // Samples
    ctx.fillStyle = "rgba(180,200,255,0.18)";
    for (const s of samples) {
      if (s.arrayVoltage == null || s.tristarPower == null) continue;
      const [x, y] = project(s.arrayVoltage, s.tristarPower, W, H, PAD);
      ctx.fillRect(x - 1, y - 1, 2, 2);
    }

    // Active curve
    if (curve) {
      ctx.strokeStyle = "#4ea3ff";
      ctx.lineWidth = 2;
      ctx.setLineDash([]);
      ctx.beginPath();
      curve.points.forEach((p, i) => {
        const [x, y] = project(p.voltage, p.power, W, H, PAD);
        if (i === 0) ctx.moveTo(x, y); else ctx.lineTo(x, y);
      });
      ctx.stroke();
    }

    // Envelope
    if (metrics) {
      ctx.strokeStyle = "#ffaa55";
      ctx.lineWidth = 1.5;
      ctx.setLineDash([5, 4]);
      ctx.beginPath();
      metrics.envelope.forEach((b, i) => {
        const [x, y] = project(b.voltage, b.pP90, W, H, PAD);
        if (i === 0) ctx.moveTo(x, y); else ctx.lineTo(x, y);
      });
      ctx.stroke();
    }

    // Suggested
    if (metrics?.recommendation && showSuggested) {
      ctx.strokeStyle = "#7ee07e";
      ctx.lineWidth = 2;
      ctx.setLineDash([2, 3, 8, 3]);
      ctx.beginPath();
      metrics.recommendation.forEach((p, i) => {
        const [x, y] = project(p.voltage, p.power, W, H, PAD);
        if (i === 0) ctx.moveTo(x, y); else ctx.lineTo(x, y);
      });
      ctx.stroke();
    }

    // Free-voltage suggested
    if (freeRecommendation && showFree) {
      ctx.strokeStyle = "#d969d9";
      ctx.lineWidth = 2;
      ctx.setLineDash([2, 2]);
      ctx.beginPath();
      freeRecommendation.forEach((p, i) => {
        const [x, y] = project(p.voltage, p.power, W, H, PAD);
        if (i === 0) ctx.moveTo(x, y); else ctx.lineTo(x, y);
      });
      ctx.stroke();
    }

    ctx.setLineDash([]);
  }, [samples, metrics, showSuggested, freeRecommendation, showFree, curve?.id]);

  return (
    <div>
      <canvas ref={canvasRef} width={1100} height={500} style="width:100%;height:auto;display:block" />
      <div style="display:flex;gap:1rem;margin-top:0.5rem;font-size:0.85rem;flex-wrap:wrap;">
        <label>
          <input type="checkbox" checked={showSuggested} onChange={(e) => setShowSuggested((e.target as HTMLInputElement).checked)} />
          {" "}Suggested curve
        </label>
        <label>
          <input type="checkbox" checked={showFree} onChange={(e) => setShowFree((e.target as HTMLInputElement).checked)} />
          {" "}<span style="color:#d969d9">Free-voltage curve</span>
        </label>
        {metrics && (
          <>
            <span>kWh: {metrics.energy.kwh.toFixed(2)}</span>
            <span>MPPT samples: {metrics.window.mpptSampleCount}</span>
            <span>Stalls: {metrics.stalls.count}</span>
          </>
        )}
      </div>
      {verdict && (
        <div class="verdict" style="margin-top:0.75rem;padding:0.6rem 0.9rem;background:var(--bg);border:1px solid var(--border);border-radius:4px;font-size:0.85rem;">
          <strong>Verdict vs previous:</strong>{" "}
          <span class={`verdict-${verdict.label.toLowerCase()}`}>{verdict.label}</span>
          {verdict.detail && (
            <span class="muted">
              {" — "}
              {verdict.detail.kwhPerHourDelta >= 0 ? "+" : ""}{verdict.detail.kwhPerHourDelta.toFixed(3)} kWh/h,{" "}
              {verdict.detail.stallsPerDayDelta >= 0 ? "+" : ""}{verdict.detail.stallsPerDayDelta.toFixed(1)} stalls/day
            </span>
          )}
          {metrics?.recommendation && (
            <button
              onClick={applySuggested}
              disabled={applyBusy}
              style="margin-left:1rem;background:var(--accent);color:white;border:0;padding:0.3rem 0.7rem;border-radius:3px;cursor:pointer;font-size:0.8rem;"
            >
              {applyBusy ? "Creating…" : "Apply suggested as new curve"}
            </button>
          )}
          {applyMsg && <div class="muted" style="margin-top:0.4rem;">{applyMsg}</div>}
        </div>
      )}
      {freeRecommendation && showFree && (
        <div class="muted" style="margin-top:0.5rem;font-size:0.8rem;">
          Free-voltage curve: {freeRecommendation.length} points from {freeRecommendation[0]?.voltage.toFixed(1)}V to {freeRecommendation[freeRecommendation.length-1]?.voltage.toFixed(1)}V
        </div>
      )}
    </div>
  );
}
